//



//<h1 id="firstHeading" class="firstHeading mw-first-heading"><h1> Rohan Kharate </h1><h1></h1></h1><h1 id="firstHeading" class="firstHeading mw-first-heading"><h1> Rohan Kharate </h1><h1></h1></h1>



//DOM Manipulation

document.getElementById('firstHeading')
//<h1 id = "firstHeading" class = " firstHeading mw-first-heading"></h1>

document.getElementById('firstHeading').innerHTML="<h1> rohan kharate </h1>"

//bhai manipule ...